`timescale 1ns / 1ps
// Testbench: symmetricFIR_tb
// Files required (generated by python script):
//   coeff_val.txt               - 6 decimal coefficients, one per line
//   input_signal_square_2.txt   - noisy signal, 3-digit hex, one per line
//   clean_signal.txt            - clean signal, 3-digit hex, one per line
//
// Output:
//   filtered_signal.txt         - filtered output, signed decimal, one per line
//
// WAVEFORM SETUP - add these three signals, all Signed Decimal:
//
//   noisy_signal      → Analog        → Min: -2100  Max: 2100
//   clean_signal      → Analog Step   → Min: -2100  Max: 2100
//   filtered_signal_disp → Analog     → Min: -2100  Max: 2100
//
// All three are in 12-bit range so Vivado autoscales them identically.
// noisy_signal  : noisy input to DUT
// clean_signal  : original clean reference (Analog Step = correct square shape)
// filtered_signal_disp : filtered output scaled back to 12-bit (filtered >> 8)
module symmetricFIR_tb ();

    localparam FILE_DIR = "";

    parameter COEFF_NUM    = 6;
    parameter COEFF_WIDTH  = 8;
    parameter DATA_DELAY   = COEFF_NUM * 2;                          // 12
    parameter DATA_WIDTH   = 12;
    parameter STAGE1_WIDTH = DATA_WIDTH + 1;                         // 13
    parameter STAGE2_WIDTH = STAGE1_WIDTH + COEFF_WIDTH + 1;         // 22
    parameter STAGE3_WIDTH = STAGE2_WIDTH + $clog2(COEFF_NUM) + 1;  // 25
    parameter OUTPUT_WIDTH = STAGE3_WIDTH;                           // 25

    // DC_GAIN = sum([6,12,22,30,34,24,24,34,30,22,12,6]) = 256 = 2^8
    localparam DC_GAIN_BITS = 8;

    // -------------------------------------------------------------------------
    // DUT signals
    // -------------------------------------------------------------------------
    reg  clk;
    reg  clr;
    reg  load;
    reg  signed [COEFF_WIDTH-1:0] coeff_value;
    reg  signed [DATA_WIDTH-1:0]  noisy_signal;
    wire signed [OUTPUT_WIDTH-1:0] filtered_signal_raw;  // raw 25-bit DUT output
    wire output_valid;

    // -------------------------------------------------------------------------
    // Waveform display signals - all 12-bit, directly comparable
    //
    // filtered_signal_disp : filtered_signal_raw >> 8
    //                        Brings output back to input amplitude scale.
    //                        Add this to waveform as "filtered signal".
    //
    // clean_signal         : plain 12-bit clean reference from file.
    //                        Set waveform style to "Analog Step" for correct
    //                        square wave appearance.
    //
    // noisy_signal is already 12-bit - add directly to waveform.
    // -------------------------------------------------------------------------
    wire signed [DATA_WIDTH-1:0] filtered_signal_disp;
    reg  signed [DATA_WIDTH-1:0] clean_signal;

    assign filtered_signal_disp = $signed(filtered_signal_raw) >>> DC_GAIN_BITS;

    // -------------------------------------------------------------------------
    // DUT instantiation
    // -------------------------------------------------------------------------
    symmetricFIR #(
        .COEFF_NUM    (COEFF_NUM),
        .COEFF_WIDTH  (COEFF_WIDTH),
        .DATA_DELAY   (DATA_DELAY),
        .DATA_WIDTH   (DATA_WIDTH),
        .STAGE1_WIDTH (STAGE1_WIDTH),
        .STAGE2_WIDTH (STAGE2_WIDTH),
        .STAGE3_WIDTH (STAGE3_WIDTH),
        .OUTPUT_WIDTH (OUTPUT_WIDTH)
    ) DUT (
        .clk             (clk),
        .clr             (clr),
        .load            (load),
        .coeff_value     (coeff_value),
        .noisy_signal    (noisy_signal),
        .filtered_signal (filtered_signal_raw),
        .output_valid    (output_valid)
    );

    //10 ns clock period (100 MHz)
    localparam CLK_PERIOD = 10;
    initial clk = 0;
    always #(CLK_PERIOD/2) clk = ~clk;

    // File handles and module-level temporaries
    integer fd_coeff, fd_input, fd_clean, fd_output;
    integer scan_ret;
    reg signed [DATA_WIDTH-1:0] clean_sample;

    // Task: Reset DUT
    task init_dut;
        begin
            clr          = 1;
            load         = 0;
            coeff_value  = 0;
            noisy_signal = 0;
            clean_signal = 0;
            repeat (8) @(negedge clk);
            clr = 0;
        end
    endtask

    // Task: Load coefficients
    task load_coeffs;
        begin
            fd_coeff = $fopen({FILE_DIR, "coeff_val.txt"}, "r");
            if (fd_coeff == 0) begin
                $display("[FATAL] Cannot open coeff_val.txt");
                $display("        Run in Tcl: cd {C:/Users/srsha/Desktop/IEEE projects/FIR_teach}");
                $finish(2);
            end
            load = 1;
            while (!$feof(fd_coeff)) begin
                scan_ret = $fscanf(fd_coeff, " %d", coeff_value);
                if (scan_ret == 1)
                    @(negedge clk);
            end
            $fclose(fd_coeff);
            load = 0;
            @(negedge clk);   //one extra cycle for coeff_valid to assert
            $display("[INFO] Coefficients loaded.");
        end
    endtask

    // Task: Stream noisy and clean signals, one sample per clock
    task stream_input;
        begin
            fd_input = $fopen({FILE_DIR, "input_signal_square_2.txt"}, "r");
            if (fd_input == 0) begin
                $display("[FATAL] Cannot open input_signal_square_2.txt");
                $display("        Run in Tcl: cd {C:/Users/srsha/Desktop/IEEE projects/FIR_teach}");
                $finish(2);
            end

            fd_clean = $fopen({FILE_DIR, "clean_signal.txt"}, "r");
            if (fd_clean == 0)
                $display("[WARN] Cannot open clean_signal.txt - clean waveform will be zero");

            while (!$feof(fd_input)) begin
                scan_ret = $fscanf(fd_input, " %h", noisy_signal);

                if (fd_clean != 0 && !$feof(fd_clean)) begin
                    scan_ret = $fscanf(fd_clean, " %h", clean_sample);
                    if (scan_ret == 1)
                        clean_signal = clean_sample;
                end

                @(negedge clk);
            end

            $fclose(fd_input);
            if (fd_clean != 0) $fclose(fd_clean);
            noisy_signal = 0;
            clean_signal = 0;
            $display("[INFO] Input streaming complete.");
        end
    endtask

    // Main flow
    initial begin
        fd_output = $fopen({FILE_DIR, "filtered_signal.txt"}, "w");
        if (fd_output == 0)
            $display("[WARN] Cannot open filtered_signal.txt - output will not be saved");

        init_dut();
        load_coeffs();
        stream_input();

        repeat (DATA_DELAY + 10) @(negedge clk);

        if (fd_output != 0) $fclose(fd_output);
        $display("[INFO] Simulation complete. Output written to filtered_signal.txt");
        $finish(2);
    end

    // -------------------------------------------------------------------------
    // Output capture - raw 25-bit value logged to file
    // Use filtered_signal_disp in waveform, filtered_signal.txt for comparison
    // -------------------------------------------------------------------------
    always @(posedge clk) begin
        if (output_valid && (fd_output != 0))
            $fdisplay(fd_output, "%0d", $signed(filtered_signal_raw));
    end

endmodule